 *=$500;set offset to 0x500

LOW=$00FF
HIGH=$FF00

;The last word address in the FORTH kernel
FORTH_LAST_KERNEL_WORD=.tmpend
FORTH_PARSE_SIZE=$20 ;In bytes
FORTH_INPUTBUFFER_SIZE=$80 ;In bytes

;A link to the previous word
FORTH_WORDOFFSET_LINK=$0
;A pointer to the name of the word (null-terminated)
FORTH_WORDOFFSET_NAME=$2
;The flags and the length of the word
FORTH_WORDOFFSET_FLAGS=$4
;The beginning of the word definition
FORTH_WORDOFFSET_DEFINITION=$6
;The beginning of the word thread (only for threaded words)
FORTH_WORDOFFSET_THREAD=$7

;Used for when FORTH should execute the word while interpreting
FORTH_WORDFLAG_IMMEDIATE=$8000
;Mask for the length of the word
FORTH_WORDFLAG_LENGTH=$7FFF

ZP_DISK=$00 ;8 bit read only
ZP_CONSOLE=$01 ;8 bit read only
ZP_SHELL_LINE=$02 ;8 bit
ZP_SHELL_OFFSET=$03 ;8 bit
ZP_TEMP=$04 ;16 bit
ZP_LASTWORD=$06 ;16 bit
ZP_BACKSTACK=$08 ;16 bit
ZP_REDBUS_ID=$0A ;16 bit
ZP_MODE_COMPILE=$0C ;16 bit
ZP_FORTH_HERE=$0E ;16 bit
ZP_FORTH_TIB=$10 ;16 bit - pointer to beginning of input buffer
ZP_FORTH_PARSEBUFFER=$12 ;16 bit pointer to beginning of parse buffer
ZP_FORTH_PARSELOC=$14 ;16 bit - location that parse is parsing 

STACK_PAGE=$0100
REDBUS_PAGE=$0200
RSTACK_PAGE=$0300
EXTERNAL_PAGE=$0400

RSTACK_START=$03FE

MMU_REDBUS_SETID=$00
MMU_REDBUS_GETID=$80
MMU_REDBUS_SETPAGE=$01
MMU_REDBUS_GETPAGE=$81
MMU_REDBUS_ENABLE=$02
MMU_REDBUS_DISABLE=$82
MMU_EMMW_SETPAGE=$03
MMU_EMMW_GETPAGE=$83
MMU_EMMW_ENABLE=$04
MMU_EMMW_DISABLE=$84
MMU_BRK_VECTOR_SET=$05
MMU_BRK_VECTOR_GET=$85
MMU_POR_SETADDRESS=$06
MMU_POR_GETADDRESS=$06

IOX_IN=REDBUS_PAGE+$00
IOX_OUT=REDBUS_PAGE+$02

KEYBOARD_START=REDBUS_PAGE+$04
KEYBOARD_END=REDBUS_PAGE+$05
KEYBOARD_CHAR=REDBUS_PAGE+$06

SCREEN_ROW=REDBUS_PAGE+$00
CURSOR_X=REDBUS_PAGE+$01
CURSOR_Y=REDBUS_PAGE+$02
CURSOR_MODE=REDBUS_PAGE+$03
BLIT_S_X=REDBUS_PAGE+$08
BLIT_S_Y=REDBUS_PAGE+$09
BLIT_O_X=REDBUS_PAGE+$0A
BLIT_O_Y=REDBUS_PAGE+$0B
BLIT_WIDTH=REDBUS_PAGE+$0C
BLIT_HEIGHT=REDBUS_PAGE+$0D
BLIT_MODE=REDBUS_PAGE+$07
BLIT_MODE_FILL=1
BLIT_MODE_INVERT=2
BLIT_MODE_SHIFT=3
SCREEN_MEMORY=REDBUS_PAGE+$10
SCREEN_WIDTH=$50
SCREEN_HEIGHT=$32
